server:
  port: 0

spring:
  application:
    name: shopping-cart

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/shopping_cart}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      client-id: shopping-cart-service-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
    consumer:
      group-id: shopping-cart-events-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
    topics:
      order-events: ${KAFKA_TOPIC_ORDER_EVENTS:shopping.order.events.v1}

feign:
  client:
    config:
      default:
        loggerLevel: full
      product-service:
        connectTimeout: 5000
        readTimeout: 5000
      warehouse-service:
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    root: INFO
    ru.yandex.practicum: DEBUG
    service: DEBUG
    controller: DEBUG
    repository: DEBUG
    client: DEBUG
    feign: DEBUG
    org.hibernate.SQL: DEBUG
    org.apache.kafka: INFO
    org.springframework.cloud.client.circuitbreaker: DEBUG

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 50
      failureRateThreshold: 50
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 10
      recordExceptions:
        - exception.InsufficientStockException
        - jakarta.ws.rs.ServiceUnavailableException
    shoppingStore:
      slidingWindowSize: 50
      failureRateThreshold: 50
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 10
      recordExceptions:
        - exception.InsufficientStockException
        - jakarta.ws.rs.ServiceUnavailableException
    warehouseService:
      slidingWindowSize: 50
      failureRateThreshold: 50
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 10
      recordExceptions:
        - exception.InsufficientStockException
        - jakarta.ws.rs.ServiceUnavailableException